apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: myjob
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: busybox
        name: myjob
        # Querying service directly
        command:
          - /bin/sh
          - "-c" 
          - "curl http://r15cookieblog/"
        resources: {}
      restartPolicy: Never
status: {}
